pipeline:
  name: child
  identifier: child
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: TXAutomate
        repoName: Tx-Automate
        build: <+input>
  stages:
    - stage:
        name: jds
        identifier: jds
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo "<+stage.variables.output>"
