apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetcore
  labels:
    app: dotnetcore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnetcore
  template:
    metadata:
      labels:
        app: dotnetcore
    spec:
      containers:
      - name: dotnetcore
        image: anuj730/harness-repo:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: dotnetcore-service
spec:
  selector:
    app: dotnetcore
  type: NodePort
  ports:
    - nodePort: 31111
      port: 80
      protocol: TCP
      targetPort: 80

