pipeline:
  identifier: Build_anujrajkumar_Tx_Automate_1704274618869
  name: DotNetPipeline
  orgIdentifier: default
  projectIdentifier: DotNetPipeline
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1704192628541
        repoName: anujrajkumar/Tx-Automate
        build: <+input>
        prCloneStrategy: SourceBranch
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Build
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: |-
                      dotnet build MyAppT/MyAppT.csproj
                      dotnet publish --configuration Release --output ./published
                      zip -r published_artifacts.zip ./published
                      ltr
              - step:
                  type: Run
                  name: Test
                  identifier: Run_3
                  spec:
                    shell: Sh
                    command: |-
                      #cd .\TestingProject\ ; dotnet test
                      wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
                      sudo dpkg -i packages-microsoft-prod.deb
                      sudo apt-get update
                      sudo apt-get install -y dotnet-sdk-5.0
                      dotnet --version
                      dotnet test TestingProject/TestingProject.csproj --logger "trx;LogFileName=testresults.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura --collect "Code coverage" /p:CoverletOutput=TestResults/Coverage/
              - step:
                  type: ArtifactoryUpload
                  name: ArtifactoryUpload_1
                  identifier: ArtifactoryUpload_1
                  spec:
                    connectorRef: jfrog
                    target: harness-artifact-dev
                    sourcePath: ./published_artifacts.zip
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        delegateSelectors:
          - windows-amd64
          - docker-delegate
        description: ""
