pipeline:
  identifier: Build_anujrajkumar_Tx_Automate_1704274618869
  name: DotNetPipeline
  orgIdentifier: default
  projectIdentifier: DotNetPipeline
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1704192628541
        repoName: anujrajkumar/Tx-Automate
        build: <+input>
        prCloneStrategy: SourceBranch
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: Restore
                  spec:
                    shell: Sh
                    command: dotnet restore
                  timeout: ""
                  type: Run
                  description: Build the Project
              - step:
                  type: Run
                  name: Build
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: dotnet build
              - step:
                  type: Run
                  name: Test
                  identifier: Run_3
                  spec:
                    shell: Sh
                    command: |-
                      #cd .\TestingProject\ ; dotnet test
                      dotnet test TestingProject/ --logger "trx;LogFileName=testresults.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura --collect "Code coverage" /p:CoverletOutput=TestResults/Coverage/
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        delegateSelectors:
          - windows-amd64
          - docker-delegate
        description: ""
